### ISSUE TITLE
Server exit

### ISSUE THREAD

**Issue by dselans** [Nitro/singularity-monitor#1]
Hi there, thanks for open sourcing the tool!

After running fine for ~1 week, the tool stopped sending metrics to insights though.

Looking through logs, this is one of the last things I saw:

```
2019-09-29 05:28:34,001     INFO [  sgmon.http] Get success: <Response [200]>
Traceback (most recent call last):
  File "/usr/local/bin/singularity-monitor", line 11, in <module>
    load_entry_point('singularity-monitor==0.0.1', 'console_scripts', 'singularity-monitor')()
  File "/usr/local/lib/python3.7/site-packages/sgmon/monitor.py", line 103, in main
    loop_forever()
  File "/usr/local/lib/python3.7/site-packages/newrelic/packages/wrapt/wrappers.py", line 522, in __call__
    args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/newrelic/api/background_task.py", line 105, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sgmon/monitor.py", line 91, in loop_forever
    insights.push_events(tasks_to_push)
  File "/usr/local/lib/python3.7/site-packages/sgmon/event.py", line 76, in push_events
    manager.remove_task(task)
  File "/usr/local/lib/python3.7/site-packages/sgmon/task.py", line 30, in remove_task
    with shelve.open(self._db_path, writeback=True) as db:
  File "/usr/local/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.7/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
```

Sadly, I did not get a chance to exec into the container to see what was running/etc.

If it happens again, I'll update this issue.

Thanks!

**Comment by sbz** [comment]
Hi @dselans, thank you for reporting that issue.

I will try to see if I can reproduce it and start investigating on this traceback soon 🤝.

**Comment by dselans** [comment]
@sbz the issue is related to the `TaskManager` - after pushing events, task removal doesn't work and `tasks.db` continues growing and growing. After `tasks.db` grows >2GB in size you start getting `Resource temporarily unavailable` errors and eventually then event pushing stops working altogether.

I wanted to fix it but I am unable to get the project to run locally on macOS. Some instructions on local dev would be great. Thanks!

**Comment by sbz** [comment]
@dselans Sorry for the delay, just found time to get back to that now. Thanks for your investigation, it will be really useful to have the steps to reproduce that behaviour in order to properly root caused it. Also, I would like to know what is your runtime environment? I couldn't reproduce it in our environment, so I would be very willing and interested to solve that after reproduction.

In order you to be able to run the project locally, I added the instructions in the section **Run** of the [README](https://github.com/Nitro/singularity-monitor/#using-python)
